---
title: "ProyectoTD2023"
autor: "Andrés Chicaiza, María Castellanos, Hugo Lucas, Adrián Blat, Yuliana Villada"
output: html_document
date: "2023-04-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)

#Cabecera digital

cab_dig1 <- "data/data/1059xlxveei79_ECGf2/27_09_2022/14.42.29_III_ECGyEXTyRESTO/cabecera_FicheroDigital.dat"

cab_info_dig <- file.info("data/data/1059xlxveei79_ECGf2/27_09_2022/14.42.29_III_ECGyEXTyRESTO/cabecera_FicheroDigital.dat")

max_cabdig1 <- cab_info_dig$size

cabecera_dig1 <- readBin(cab_dig1,integer(),n = max_cabdig1,size = 1, signed = F)


#Fichero digital

fich_dig1 <- "data/data/1059xlxveei79_ECGf2/27_09_2022/14.42.29_III_ECGyEXTyRESTO/ficheroDigital.dat"

fich_info <- file.info("data/data/1059xlxveei79_ECGf2/27_09_2022/14.42.29_III_ECGyEXTyRESTO/ficheroDigital.dat")

max_fichdig1 <- fich_info$size

fichero_dig1 <- readBin(fich_dig1,integer(),n = max_fichdig1,size = 1, signed = F)

HR1 <- fichero_dig1[seq(from=1, to = length(fichero_dig1), by = 9)]
HR2 <- fichero_dig1[seq(from=2, to = length(fichero_dig1), by = 9)]
MHR <- fichero_dig1[seq(from=3, to = length(fichero_dig1), by = 9)]
TOCO <- fichero_dig1[seq(from=4, to = length(fichero_dig1), by = 9)]
MSpO2 <- fichero_dig1[seq(from=5, to = length(fichero_dig1), by = 9)]
VCP <- fichero_dig1[seq(from=6, to = length(fichero_dig1), by = 9)]
Psistolica <- fichero_dig1[seq(from=7, to = length(fichero_dig1), by = 9)]
Pdiastolica <- fichero_dig1[seq(from=8, to = length(fichero_dig1), by = 9)]
Pmedia <- fichero_dig1[seq(from=9, to = length(fichero_dig1), by = 9)]

mediaVCP <- mean(VCP)

lista <- list(HR1, HR2, MHR, TOCO, MSpO2, VCP, Psistolica, Pdiastolica, Pmedia)

nombres <- c("HR1", "HR2", "MHR", "TOCO", "MSpO2", "VCP", "Psistolica", "Pdiastolica", "Pmedia")

dato_dig1 <- as.data.frame(lista)

colnames(dato_dig1) <- nombres

tiempo <- seq(0, length.out = nrow(dato_dig1), by = 0.25)
tiempo <- head(tiempo, 2604)


dato_dig1 <- dato_dig1 %>%
    mutate(tiempo = tiempo)

hora <- ((((length(dato_dig1) / 9) / 4) / 60) / 60)
min <- ((hora - floor(hora)) * 60)
seg <- ((min - floor(min))) * 60
  
tiempo_digital <- cbind(hora, min, seg)

dato_dig1
```

```{r}
ggplot(dato_dig1, aes(tiempo,HR1)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,HR2)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,MHR)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,TOCO)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,MSpO2)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,VCP)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Psistolica)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Pdiastolica)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Pmedia)) + geom_line(size=0.2)
```

```{r}
#Cabecera Analogica

cab_ana1 <- "data/data/1059xlxveei79_ECGf2/27_09_2022/14.42.29_III_ECGyEXTyRESTO/cabecera_FicheroAnalogico.dat"

cab_info_ana <- file.info("data/data/1059xlxveei79_ECGf2/27_09_2022/14.42.29_III_ECGyEXTyRESTO/cabecera_FicheroAnalogico.dat")

max_cabana1 <- cab_info_ana$size

cabecera_ana1.1 <- readBin(cab_dig1,integer(),n = max_cabana1,size = 1, signed = F)
cabecera_ana1.2 <- readBin(cab_dig1,integer(),n = max_cabana1,size = 2, signed = T)

# Fichero Analogico

fich_ana1 <- "data/data/1059xlxveei79_ECGf2/27_09_2022/14.42.29_III_ECGyEXTyRESTO/ficheroAnalogico.dat"
fich_info_ana <- file.info("data/data/1059xlxveei79_ECGf2/27_09_2022/14.42.29_III_ECGyEXTyRESTO/ficheroAnalogico.dat")
max_fichanal <- fich_info_ana$size

fichero_ana1 <- readBin(fich_ana1, integer(), n = max_fichanal, size = 2, signed = T)

Frec <- 1000

tiempo_ana1 <- seq(from = 0, to = (length(fichero_ana1)-1)/Frec, by = 1/Frec)

dato_ana1 <- data.frame(tiempo_ana1, fichero_ana1)

h <- ((length(dato_ana1)/Frec)/60)/60
min <- ((h - floor(h)) * 60)
seg <- ((min - floor(min)) * 60)

time_ana1 <- cbind(h,min,seg)



```


```{r}
ggplot(dato_ana1, aes(tiempo_ana1,fichero_ana1)) + geom_line()
ggplot(dato_ana1, aes(tiempo_ana1,fichero_ana1)) + geom_line(size = 1) + lims(x = c(692,700.03), y = c(-198,957))
```



```{r}
#Para la carpeta 0519

#Cabecera digital

# Se define la ubicación del archivo que contiene la cabecera digital.
cab_dig1 <- "data/data/0519xxxiii14/06_02_2023/14.20.34/cabecera_FicheroDigital.dat"

# Se obtiene información sobre la cabecera digital, como su tamaño y fecha de creación.
cab_info_dig <- file.info("data/data/0519xxxiii14/06_02_2023/14.20.34/cabecera_FicheroDigital.dat")

# Se extrae el tamaño del archivo de la cabecera digital.
max_cabdig1 <- cab_info_dig$size

# Se lee el contenido del archivo de cabecera digital y se guarda en un vector llamado "cabecera_dig1" utilizando la función "readBin()".
cabecera_dig1 <- readBin(cab_dig1,integer(),n = max_cabdig1,size = 1, signed = F)


#Fichero digital

# Se define la ubicación del archivo.
fich_dig1 <- "data/data/0519xxxiii14/06_02_2023/14.20.34/FicheroDigital.dat"

# Se obtiene información sobre el archivo, como su tamaño y fecha de creación.
fich_info <- file.info("data/data/0519xxxiii14/06_02_2023/14.20.34/FicheroDigital.dat")

# Se extrae el tamaño del archivo de registro digital.
max_fichdig1 <- fich_info$size

# Se lee el contenido del archivo y se guarda en un vector llamado "fichero_dig1" utilizando la función "readBin()".
fichero_dig1 <- readBin(fich_dig1,integer(),n = max_fichdig1,size = 1, signed = F)

# Se divide el vector "fichero_dig1" en vectores separados para cada parámetro de interés.
HR1 <- fichero_dig1[seq(from=1, to = length(fichero_dig1), by = 9)]
HR2 <- fichero_dig1[seq(from=2, to = length(fichero_dig1), by = 9)]
MHR <- fichero_dig1[seq(from=3, to = length(fichero_dig1), by = 9)]
TOCO <- fichero_dig1[seq(from=4, to = length(fichero_dig1), by = 9)]
MSpO2 <- fichero_dig1[seq(from=5, to = length(fichero_dig1), by = 9)]
VCP <- fichero_dig1[seq(from=6, to = length(fichero_dig1), by = 9)]
Psistolica <- fichero_dig1[seq(from=7, to = length(fichero_dig1), by = 9)]
Pdiastolica <- fichero_dig1[seq(from=8, to = length(fichero_dig1), by = 9)]
Pmedia <- fichero_dig1[seq(from=9, to = length(fichero_dig1), by = 9)]

# Se calcula la media de la variable "
mediaVCP <- mean(VCP)

#Se crea una lista que contiene las variables 
lista <- list(HR1, HR2, MHR, TOCO, MSpO2, VCP, Psistolica, Pdiastolica, Pmedia)

nombres <- c("HR1", "HR2", "MHR", "TOCO", "MSpO2", "VCP", "Psistolica", "Pdiastolica", "Pmedia")

#Se crea un data frame a partir de la lista
dato_dig1 <- as.data.frame(lista)

colnames(dato_dig1) <- nombres

#Se Crea un vector llamado "tiempo" que va desde 0 hasta el número de filas del data frame "dato_dig1" con un intervalo de 0.25.
tiempo <- seq(0, length.out = nrow(dato_dig1), by = 0.25)

#Toma las primeras 19452 filas del vector "tiempo" y las asigna a la variable "tiempo".
tiempo <- head(tiempo, 19452)


dato_dig1 <- dato_dig1 %>%
    mutate(tiempo = tiempo)

hora <- ((((length(dato_dig1) / 9) / 4) / 60) / 60)
min <- ((hora - floor(hora)) * 60)
seg <- ((min - floor(min))) * 60
  
tiempo_digital <- cbind(hora, min, seg)

dato_dig1
```


```{r}
ggplot(dato_dig1, aes(tiempo,HR1)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,HR2)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,MHR)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,TOCO)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,MSpO2)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,VCP)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Psistolica)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Pdiastolica)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Pmedia)) + geom_line(size=0.2)
```

```{r}
#Cabecera Analogica

cab_ana1 <- "data/data/0519xxxiii14/06_02_2023/14.20.34/cabecera_FicheroAnalogico.dat"

cab_info_ana <- file.info("data/data/0519xxxiii14/06_02_2023/14.20.34/cabecera_FicheroAnalogico.dat")

max_cabana1 <- cab_info_ana$size

cabecera_ana1.1 <- readBin(cab_dig1,integer(),n = max_cabana1,size = 1, signed = F)
cabecera_ana1.2 <- readBin(cab_dig1,integer(),n = max_cabana1,size = 2, signed = T)

# Fichero Analogico

fich_ana1 <- "data/data/0519xxxiii14/06_02_2023/14.20.34/FicheroAnalogico.dat"
fich_info_ana <- file.info("data/data/0519xxxiii14/06_02_2023/14.20.34/FicheroAnalogico.dat")
max_fichanal <- fich_info_ana$size

fichero_ana1 <- readBin(fich_ana1, integer(), n = max_fichanal, size = 2, signed = T)

Frec <- 1000

tiempo_ana1 <- seq(from = 0, to = (length(fichero_ana1)-1)/Frec, by = 1/Frec)

dato_ana1 <- data.frame(tiempo_ana1, fichero_ana1)

h <- ((length(dato_ana1)/Frec)/60)/60
min <- ((h - floor(h)) * 60)
seg <- ((min - floor(min)) * 60)

time_ana1 <- cbind(h,min,seg)
```


```{r}
ggplot(dato_ana1, aes(tiempo_ana1,fichero_ana1)) + geom_line()
ggplot(dato_ana1, aes(tiempo_ana1,fichero_ana1)) + geom_line(size = 1) + lims(x = c(692,700.03), y = c(-198,957))
```














```{r}
#Para la carpeta 0795xalvii8a7

#Cabecera digital
cab_dig1 <- "data/data/0795xalvii8a7/27_09_2022/10.11.00/cabecera_FicheroDigital.dat"
cab_info_dig <- file.info("../data/data/0795xalvii8a7/27_09_2022/10.11.00/cabecera_FicheroDigital.dat")
max_cabdig1 <- cab_info_dig$size
cabecera_dig1 <- readBin(cab_dig1,integer(),n = max_cabdig1,size = 1, signed = F)

#Fichero digital
fich_dig1 <- "data/data/0795xalvii8a7/27_09_2022/10.11.00/ficheroDigital.dat"
fich_info <- file.info("data/data/0795xalvii8a7/27_09_2022/10.11.00/ficheroDigital.dat")
max_fichdig1 <- fich_info$size
fichero_dig1 <- readBin(fich_dig1,integer(),n = max_fichdig1,size = 1, signed = F)

HR1 <- fichero_dig1[seq(from=1, to = length(fichero_dig1), by = 9)]
HR2 <- fichero_dig1[seq(from=2, to = length(fichero_dig1), by = 9)]
MHR <- fichero_dig1[seq(from=3, to = length(fichero_dig1), by = 9)]
TOCO <- fichero_dig1[seq(from=4, to = length(fichero_dig1), by = 9)]
MSpO2 <- fichero_dig1[seq(from=5, to = length(fichero_dig1), by = 9)]
VCP <- fichero_dig1[seq(from=6, to = length(fichero_dig1), by = 9)]
Psistolica <- fichero_dig1[seq(from=7, to = length(fichero_dig1), by = 9)]
Pdiastolica <- fichero_dig1[seq(from=8, to = length(fichero_dig1), by = 9)]
Pmedia <- fichero_dig1[seq(from=9, to = length(fichero_dig1), by = 9)]

mediaVCP <- mean(VCP)
lista <- list(HR1, HR2, MHR, TOCO, MSpO2, VCP, Psistolica, Pdiastolica, Pmedia)
nombres <- c("HR1", "HR2", "MHR", "TOCO", "MSpO2", "VCP", "Psistolica", "Pdiastolica", "Pmedia")
dato_dig1 <- as.data.frame(lista)
colnames(dato_dig1) <- nombres
tiempo <- seq(0, length.out = nrow(dato_dig1), by = 0.25)
tiempo <- head(tiempo, 2604)


dato_dig1 <- dato_dig1 %>%
    mutate(tiempo = tiempo)

hora <- ((((length(dato_dig1) / 9) / 4) / 60) / 60)
min <- ((hora - floor(hora)) * 60)
seg <- ((min - floor(min))) * 60
  
tiempo_digital <- cbind(hora, min, seg)
dato_dig1

```

```{r}
ggplot(dato_dig1, aes(tiempo,HR1)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,HR2)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,MHR)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,TOCO)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,MSpO2)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,VCP)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Psistolica)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Pdiastolica)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Pmedia)) + geom_line(size=0.2)

```


```{r}
#Cabecera Analogica
cab_ana1 <- "data/data/0795xalvii8a7/27_09_2022/10.11.00/cabecera_FicheroAnalogico.dat"
cab_info_ana <- file.info("data/data/0795xalvii8a7/27_09_2022/10.11.00/cabecera_FicheroAnalogico.dat")
max_cabana1 <- cab_info_ana$size
cabecera_ana1.1 <- readBin(cab_dig1,integer(),n = max_cabana1,size = 1, signed = F)
cabecera_ana1.2 <- readBin(cab_dig1,integer(),n = max_cabana1,size = 2, signed = T)


# Fichero Analogico
fich_ana1 <- "data/data/0795xalvii8a7/27_09_2022/10.11.00/ficheroAnalogico.dat"
fich_info_ana <- file.info("data/data/0795xalvii8a7/27_09_2022/10.11.00/ficheroAnalogico.dat")
max_fichanal <- fich_info_ana$size
fichero_ana1 <- readBin(fich_ana1, integer(), n = max_fichanal, size = 2, signed = T)

Frec <- 1000
tiempo_ana1 <- seq(from = 0, to = (length(fichero_ana1)-1)/Frec, by = 1/Frec)

dato_ana1 <- data.frame(tiempo_ana1, fichero_ana1)

h <- ((length(dato_ana1)/Frec)/60)/60
min <- ((h - floor(h)) * 60)
seg <- ((min - floor(min)) * 60)

time_ana1 <- cbind(h,min,seg)

```



```{r}
#Cabecera digital
cab_dig1 <- "data/data/0795xalvii8a7/27_09_2022/10.11.12/cabecera_FicheroDigital.dat"
cab_info_dig <- file.info("data/data/0795xalvii8a7/27_09_2022/10.11.12/cabecera_FicheroDigital.dat")
max_cabdig1 <- cab_info_dig$size
cabecera_dig1 <- readBin(cab_dig1,integer(),n = max_cabdig1,size = 1, signed = F)

#Fichero digital
fich_dig1 <- "data/data/0795xalvii8a7/27_09_2022/10.11.12/ficheroDigital.dat"
fich_info <- file.info("data/data/0795xalvii8a7/27_09_2022/10.11.12/ficheroDigital.dat")
max_fichdig1 <- fich_info$size
fichero_dig1 <- readBin(fich_dig1,integer(),n = max_fichdig1,size = 1, signed = F)

HR1 <- fichero_dig1[seq(from=1, to = length(fichero_dig1), by = 9)]
HR2 <- fichero_dig1[seq(from=2, to = length(fichero_dig1), by = 9)]
MHR <- fichero_dig1[seq(from=3, to = length(fichero_dig1), by = 9)]
TOCO <- fichero_dig1[seq(from=4, to = length(fichero_dig1), by = 9)]
MSpO2 <- fichero_dig1[seq(from=5, to = length(fichero_dig1), by = 9)]
VCP <- fichero_dig1[seq(from=6, to = length(fichero_dig1), by = 9)]
Psistolica <- fichero_dig1[seq(from=7, to = length(fichero_dig1), by = 9)]
Pdiastolica <- fichero_dig1[seq(from=8, to = length(fichero_dig1), by = 9)]
Pmedia <- fichero_dig1[seq(from=9, to = length(fichero_dig1), by = 9)]

mediaVCP <- mean(VCP)
lista <- list(HR1, HR2, MHR, TOCO, MSpO2, VCP, Psistolica, Pdiastolica, Pmedia)
nombres <- c("HR1", "HR2", "MHR", "TOCO", "MSpO2", "VCP", "Psistolica", "Pdiastolica", "Pmedia")
dato_dig1 <- as.data.frame(lista)
colnames(dato_dig1) <- nombres
tiempo <- seq(0, length.out = nrow(dato_dig1), by = 0.25)
tiempo <- head(tiempo, 4372)


dato_dig1 <- dato_dig1  %>%
    mutate(tiempo = tiempo)

hora <- ((((length(dato_dig1) / 9) / 4) / 60) / 60)
min <- ((hora - floor(hora)) * 60)
seg <- ((min - floor(min))) * 60
  
tiempo_digital <- cbind(hora, min, seg)
dato_dig1
```


```{r}

ggplot(dato_dig1, aes(tiempo,HR1)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,HR2)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,MHR)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,TOCO)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,MSpO2)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,VCP)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Psistolica)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Pdiastolica)) + geom_line(size=0.2)
ggplot(dato_dig1, aes(tiempo,Pmedia)) + geom_line(size=0.2)

```



```{r}
#Cabecera Analogica
cab_ana1 <- "data/data/0795xalvii8a7/27_09_2022/10.11.12/cabecera_FicheroAnalogico.dat"
cab_info_ana <- file.info("data/data/0795xalvii8a7/27_09_2022/10.11.12/cabecera_FicheroAnalogico.dat")
max_cabana1 <- cab_info_ana$size
cabecera_ana1.1 <- readBin(cab_dig1,integer(),n = max_cabana1,size = 1, signed = F)
cabecera_ana1.2 <- readBin(cab_dig1,integer(),n = max_cabana1,size = 2, signed = T)

# Fichero Analogico
fich_ana1 <- "data/data/0795xalvii8a7/27_09_2022/10.11.12/ficheroAnalogico.dat"
fich_info_ana <- file.info("data/data/0795xalvii8a7/27_09_2022/10.11.12/ficheroAnalogico.dat")
max_fichanal <- fich_info_ana$size
fichero_ana1 <- readBin(fich_ana1, integer(), n = max_fichanal, size = 2, signed = T)
Frec <- 1000
tiempo_ana1 <- seq(from = 0, to = (length(fichero_ana1)-1)/Frec, by = 1/Frec)

dato_ana1 <- data.frame(tiempo_ana1, fichero_ana1)

h <- ((length(dato_ana1)/Frec)/60)/60
min <- ((h - floor(h)) * 60)
seg <- ((min - floor(min)) * 60)

time_ana1 <- cbind(h,min,seg)
```



